#!/usr/bin/env bash

echo "Entered local command hook"

if [ "$BUILDKITE_COMMAND" = "buildkite-agent pipeline upload" ]; then
    echo "Pipeline upload step"
    eval $BUILDKITE_COMMAND
else
    ./$BUILDKITE_COMMAND
fi

echo "Exited local command hook"